##############################################################################
# Falco Runtime Security — Detect suspicious behavior in running containers
#
# Falco watches syscalls and K8s audit logs to catch:
# - Shell spawned in container
# - Sensitive file access (/etc/shadow, /etc/passwd)
# - Unexpected network connections
# - Container escape attempts
# - Privilege escalation
##############################################################################

# Falco custom rules (merged with default rules)
apiVersion: v1
kind: ConfigMap
metadata:
  name: falco-custom-rules
  namespace: falco
  labels:
    app: falco
data:
  custom-rules.yaml: |
    ##################################################################
    # Custom Falco Rules for SRE Platform
    ##################################################################

    # ── Shell Access in Production Containers ────────────────────────
    - rule: Shell Spawned in Production Container
      desc: >
        Detect when a shell is spawned inside a production container.
        This could indicate an attacker or unauthorized debugging.
      condition: >
        spawned_process
        and container
        and k8s.ns.name = "production"
        and proc.name in (bash, sh, zsh, dash, ash, csh)
        and not proc.pname in (crond, supervisord)
      output: >
        Shell spawned in production (user=%user.name pod=%k8s.pod.name
        ns=%k8s.ns.name container=%container.name cmd=%proc.cmdline
        parent=%proc.pname)
      priority: WARNING
      tags: [container, shell, production]

    # ── Sensitive File Read ──────────────────────────────────────────
    - rule: Read Sensitive Files in Container
      desc: Detect when sensitive files are read inside containers
      condition: >
        open_read
        and container
        and fd.name in (/etc/shadow, /etc/passwd, /etc/kubernetes/admin.conf)
        and not proc.name in (su, sudo, sshd)
      output: >
        Sensitive file read (user=%user.name file=%fd.name pod=%k8s.pod.name
        ns=%k8s.ns.name cmd=%proc.cmdline)
      priority: CRITICAL
      tags: [container, filesystem, sensitive]

    # ── Unexpected Outbound Connection ───────────────────────────────
    - rule: Unexpected Outbound Connection from Database
      desc: Database pods should not make outbound connections
      condition: >
        outbound
        and container
        and k8s.ns.name = "production"
        and k8s.pod.label.app = "database"
        and not fd.sport in (5432, 53)
      output: >
        Unexpected outbound connection from database (pod=%k8s.pod.name
        dest=%fd.sip:%fd.sport cmd=%proc.cmdline)
      priority: CRITICAL
      tags: [network, database, exfiltration]

    # ── Container Escape Attempt ─────────────────────────────────────
    - rule: Container Escape via Mount
      desc: Detect attempts to mount host filesystem
      condition: >
        evt.type = mount
        and container
        and evt.arg.source startswith "/host"
      output: >
        Possible container escape via mount (user=%user.name
        pod=%k8s.pod.name source=%evt.arg.source cmd=%proc.cmdline)
      priority: CRITICAL
      tags: [container, escape, mount]

    # ── Privilege Escalation ─────────────────────────────────────────
    - rule: Setuid/Setgid Binary Execution
      desc: Detect execution of setuid/setgid binaries in containers
      condition: >
        spawned_process
        and container
        and (proc.is_exe_upper_layer = true)
        and user.uid = 0
        and not proc.name in (sudo, su)
      output: >
        Setuid binary executed as root (user=%user.name binary=%proc.name
        pod=%k8s.pod.name ns=%k8s.ns.name)
      priority: WARNING
      tags: [container, privilege_escalation]

    # ── Crypto Mining Detection ──────────────────────────────────────
    - rule: Crypto Mining Activity
      desc: Detect processes commonly associated with crypto mining
      condition: >
        spawned_process
        and container
        and (proc.name in (xmrig, minerd, minergate, cpuminer)
             or proc.cmdline contains "stratum+tcp"
             or proc.cmdline contains "pool.minexmr")
      output: >
        Crypto mining detected (pod=%k8s.pod.name ns=%k8s.ns.name
        process=%proc.name cmd=%proc.cmdline)
      priority: CRITICAL
      tags: [container, crypto_mining]

    # ── K8s API Suspicious Access ────────────────────────────────────
    - rule: Unauthorized K8s API Access
      desc: Detect pods accessing the K8s API server without expected SA
      condition: >
        outbound
        and container
        and fd.sip = "10.96.0.1"
        and fd.sport = 443
        and not k8s.pod.label.app in (argocd, prometheus, vault)
      output: >
        Unexpected K8s API access (pod=%k8s.pod.name ns=%k8s.ns.name
        cmd=%proc.cmdline)
      priority: WARNING
      tags: [kubernetes, api, unauthorized]
