apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot", "on-demand"]
    - key: node.kubernetes.io/instance-type
      operator: In
      values:
        - m5.large
        - m5.xlarge
        - m5a.large
        - m5a.xlarge
        - m6i.large
        - m6i.xlarge
    - key: topology.kubernetes.io/zone
      operator: In
      values:
        - us-east-1a
        - us-east-1b
        - us-east-1c
  limits:
    resources:
      cpu: "100"
      memory: 400Gi
  providerRef:
    name: default
  consolidation:
    enabled: true
  ttlSecondsAfterEmpty: 30
  ttlSecondsUntilExpired: 2592000  # 30 days
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  subnetSelector:
    karpenter.sh/discovery: ecommerce-production
  securityGroupSelector:
    karpenter.sh/discovery: ecommerce-production
  amiFamily: Bottlerocket
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 50Gi
        volumeType: gp3
        encrypted: true
  tags:
    Project: ecommerce
    ManagedBy: karpenter
