##############################################################################
# Cluster-wide RBAC — Roles that apply across all namespaces
#
# Principle of least privilege:
# - cluster-viewer: Read-only access for on-call engineers
# - cluster-admin-sre: Full access for SRE team (not default cluster-admin)
# - security-auditor: Read access to security-relevant resources
##############################################################################

# ── Cluster Viewer (On-Call / Read-Only) ────────────────────────────────
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-viewer
  labels:
    rbac.sre/purpose: on-call
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints", "configmaps", "events", "namespaces", "nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "statefulsets", "daemonsets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses", "networkpolicies"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "list", "watch"]
  # Allow reading pod logs for debugging
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list"]
  # Allow port-forward for debugging
  - apiGroups: [""]
    resources: ["pods/portforward"]
    verbs: ["create"]

---
# ── SRE Admin (Elevated but not cluster-admin) ─────────────────────────
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sre-admin
  labels:
    rbac.sre/purpose: platform-management
rules:
  # Full access to workloads
  - apiGroups: ["", "apps", "batch", "autoscaling"]
    resources: ["*"]
    verbs: ["*"]
  # Manage networking
  - apiGroups: ["networking.k8s.io"]
    resources: ["*"]
    verbs: ["*"]
  # Manage RBAC within namespaces
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs: ["*"]
  # Read cluster-level RBAC (but not modify — requires separate approval)
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["clusterroles", "clusterrolebindings"]
    verbs: ["get", "list", "watch"]
  # Manage Argo Rollouts
  - apiGroups: ["argoproj.io"]
    resources: ["rollouts", "analysistemplates", "analysisruns"]
    verbs: ["*"]
  # Read node information
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  # CANNOT delete namespaces or PVs (safety)
  - apiGroups: [""]
    resources: ["namespaces", "persistentvolumes"]
    verbs: ["get", "list", "watch"]

---
# ── Security Auditor ────────────────────────────────────────────────────
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: security-auditor
  labels:
    rbac.sre/purpose: compliance
rules:
  # Read all RBAC
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  # Read network policies
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["get", "list", "watch"]
  # Read pod security
  - apiGroups: [""]
    resources: ["pods", "serviceaccounts", "secrets"]
    verbs: ["get", "list", "watch"]
  # Read security contexts
  - apiGroups: ["policy"]
    resources: ["podsecuritypolicies"]
    verbs: ["get", "list", "watch"]
  # Read OPA constraints
  - apiGroups: ["constraints.gatekeeper.sh"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["templates.gatekeeper.sh"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]

---
# ── ClusterRoleBindings ─────────────────────────────────────────────────
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sre-team-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sre-admin
subjects:
  - kind: Group
    name: sre-team
    apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oncall-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-viewer
subjects:
  - kind: Group
    name: oncall-engineers
    apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: security-team-auditor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: security-auditor
subjects:
  - kind: Group
    name: security-team
    apiGroup: rbac.authorization.k8s.io
