##############################################################################
# CIS Kubernetes Benchmark — Automated compliance checks
#
# Based on CIS Kubernetes Benchmark v1.8. Implements checks as:
# - kube-bench CronJob (runs weekly)
# - Prometheus alerts for critical findings
# - Results stored as ConfigMap for audit trail
##############################################################################

# ── kube-bench CronJob ──────────────────────────────────────────────────
apiVersion: batch/v1
kind: CronJob
metadata:
  name: kube-bench-cis
  namespace: security
  labels:
    app: kube-bench
    compliance: cis-benchmark
spec:
  schedule: "0 6 * * 0"  # Weekly on Sunday at 6 AM UTC
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: kube-bench
        spec:
          hostPID: true
          restartPolicy: Never
          containers:
            - name: kube-bench
              image: aquasec/kube-bench:v0.7.1
              command:
                - /bin/sh
                - -c
                - |
                  # Run CIS benchmark and save results
                  kube-bench run --targets node,policies --json > /tmp/results.json
                  kube-bench run --targets node,policies > /tmp/results.txt

                  # Count pass/fail/warn
                  PASS=$(cat /tmp/results.json | grep -c '"status": "PASS"' || echo "0")
                  FAIL=$(cat /tmp/results.json | grep -c '"status": "FAIL"' || echo "0")
                  WARN=$(cat /tmp/results.json | grep -c '"status": "WARN"' || echo "0")

                  echo "================================================================"
                  echo "  CIS Kubernetes Benchmark Results"
                  echo "  Date: $(date -u)"
                  echo "  PASS: $PASS | FAIL: $FAIL | WARN: $WARN"
                  echo "================================================================"
                  cat /tmp/results.txt

                  # Store results as ConfigMap for audit
                  kubectl create configmap cis-benchmark-latest \
                    --from-file=results.json=/tmp/results.json \
                    --from-file=results.txt=/tmp/results.txt \
                    --from-literal=pass=$PASS \
                    --from-literal=fail=$FAIL \
                    --from-literal=warn=$WARN \
                    --from-literal=date="$(date -u)" \
                    -n security --dry-run=client -o yaml | kubectl apply -f -

                  # Exit with failure if critical checks fail
                  if [ "$FAIL" -gt "5" ]; then
                    echo "CRITICAL: More than 5 CIS checks failed"
                    exit 1
                  fi
              volumeMounts:
                - name: var-lib-etcd
                  mountPath: /var/lib/etcd
                  readOnly: true
                - name: etc-kubernetes
                  mountPath: /etc/kubernetes
                  readOnly: true
          volumes:
            - name: var-lib-etcd
              hostPath:
                path: /var/lib/etcd
            - name: etc-kubernetes
              hostPath:
                path: /etc/kubernetes
          serviceAccountName: kube-bench-sa

---
# Service account for kube-bench
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-bench-sa
  namespace: security

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-bench-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-viewer
subjects:
  - kind: ServiceAccount
    name: kube-bench-sa
    namespace: security

---
##############################################################################
# Key CIS Controls Checklist (manual reference)
#
# 1.1.x  Control Plane Config Files
#        - API server pod spec permissions (644)
#        - etcd data directory permissions (700)
#
# 1.2.x  API Server
#        - Disable anonymous auth
#        - Enable RBAC authorization
#        - Enable audit logging
#        - Set --kubelet-certificate-authority
#
# 2.x    etcd
#        - Encrypt data at rest
#        - Use TLS for peer communication
#
# 3.x    Control Plane Configuration
#        - Rotate encryption keys regularly
#        - Enable EventRateLimit admission controller
#
# 4.x    Worker Nodes
#        - kubelet authentication/authorization
#        - Protect kubelet serving certificate
#        - Set readOnlyPort to 0
#
# 5.x    Policies
#        - RBAC least privilege
#        - Pod Security Standards
#        - Network policies
#        - Limit secrets in env vars
##############################################################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: cis-controls-checklist
  namespace: security
data:
  checklist.md: |
    # CIS Kubernetes Benchmark Controls

    ## Critical (Must Fix)
    - [ ] 1.2.1: Anonymous auth disabled on API server
    - [ ] 1.2.6: RBAC authorization enabled
    - [ ] 1.2.22: Audit logging enabled
    - [ ] 2.1: etcd encrypted at rest
    - [ ] 4.2.1: kubelet anonymous auth disabled
    - [ ] 5.1.1: Cluster-admin role usage minimized
    - [ ] 5.2.1: Pod Security Standards enforced

    ## Important (Should Fix)
    - [ ] 1.2.16: Admission controllers enabled
    - [ ] 1.3.6: RotateKubeletServerCertificate enabled
    - [ ] 4.1.1: kubelet service file permissions
    - [ ] 5.1.6: Service account token automount disabled
    - [ ] 5.3.1: Default network policies applied

    ## Advisory (Best Practice)
    - [ ] 1.2.29: EventRateLimit admission controller
    - [ ] 4.2.11: Protect kernel defaults
    - [ ] 5.7.1: Use namespace-scoped resources
