apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
   name: sre-demo-alerts
   namespace: monitoring
   labels:
      release: prometheus
spec:
   groups:
    - name: sre-demo-pod-alerts
      rules:
       #Alerts if any pod ready for more than 5 minutes 
       - alert: PodNotReady
         expr: kube_pod_status_ready{namespace="sre-demo", condition="true"} == 0
         for: 5m
         labels:
            severity: warning
         annotations:
            summary: "Pod {{ $labels.pod }} is not ready"
            description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} has been not ready for more than 5 minutes."
       #Alert if pod restars more than 3 times in 10 minutes 
       - alert: PodCrashLooping
         expr: increase(kube_pod_container_status_restarts_total{namespace="sre-demo"}[10m]) > 3
         for: 1m
         labels:
            severity: critical
         annotations:
            summary: "Pod {{ $labels.pod }} is crash looping"
            description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} has restarted more than 3 times in the last 10 minutes."
       #Alert if error rate is above 5%
       - alert: HighErrorRate
         expr: (sum(rate(http_requests_total{namespace="sre-demo", status=~"5.."}[5m])) / sum(rate(http_requests_total{namespace="sre-demo"}[5m]))) > 0.05
         for: 2m
         labels:
            severity: critical
         annotations:
            summary: "High error rate in sre-demo"
            description: "Error rate is above 5% for the last 2 minutes."
